### ISSUE TITLE
Exercise ICQ functionalities in dapp-orchestration-basics

### ISSUE THREAD

**Issue by LuqiPan** [Agoric/dapp-orchestration-basics#12]
```[tasklist]
### Dependencies
- [ ] https://github.com/Agoric/agoric-sdk/issues/9890
- [ ] https://github.com/Agoric/agoric-sdk/issues/9610
- [ ] https://github.com/Agoric/dapp-orchestration-basics/pull/37
```

**Comment by Jovonni** [comment]
when I try to use `remoteAccount.getBalance(amt.brand)`, the ICQ throws:
```console
2024-08-13T04:07:43.500Z SwingSet: ls: v42: Error#1: Queries not available for chain osmosislocal
```


`localAccount.getBalance(amt.brand)` does return a `vow`

**Comment by dckc** [comment]
looks to me like this depends on this too
 - https://github.com/Agoric/agoric-sdk/issues/9890

maybe not, but conservatively, I added it to the deps. feel free to undo, @LuqiPan @0xpatrickdev
