### ISSUE TITLE
Security review of new transactions - MN Partner Checklist

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/dapp-orchestration-basics#45]
Per previous [discussion](https://agoricopco.slack.com/archives/C07EHMM31NW/p1726656025631609), as we prepare to take dapp orchestration basics to mainnet, we will need to engage the [mainnet partner checklist](https://docs.google.com/document/d/1UYq7hzSKBwZcRZnpIAUN5Lm78AOGILVaNPoPJxxLdLo/edit)

**Comment by turadg** [comment]
No longer taking this contract to Mainnet
